# Generated by Django 2.0.6 on 2018-10-13 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='body',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='barcode',
            field=models.ImageField(blank=True, null=True, upload_to='users/%Y/%m/%D/'),
        ),
    ]
