# Generated by Django 2.0.6 on 2018-10-13 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20181013_1553'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='barcode',
            new_name='employeeBarcode',
        ),
    ]
