# Generated by Django 2.0.6 on 2018-10-13 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20181013_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='employeeID',
            field=models.IntegerField(default=425363),
            preserve_default=False,
        ),
    ]
