# Generated by Django 2.0.6 on 2018-10-13 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20181013_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='employeeBarcode',
            field=models.ImageField(blank=True, null=True, upload_to='users/'),
        ),
    ]
